Repository CSC207-2022F-UofT/course-project-group-93, pull requests merged in 2022-12, with the labels that each got.

#81 Added stamina, difficulty levels, game states, refactored the game panel
  src/main/java/Main.java
  src/main/java/adapters/default_game/GamePanelController.java
  src/main/java/adapters/default_game/GamePanelPresenter.java
  src/main/java/entities/default_game/Player.java
  src/main/java/use_cases/default_game/CollisionHandler.java
  src/main/java/use_cases/default_game/IGamePanelInputBoundary.java
  src/main/java/use_cases/default_game/IGamePanelOutputBoundary.java
  src/main/java/use_cases/default_game/MazeInteractor.java
  src/main/java/use_cases/default_game/screenManager.java
  src/main/resources/mazes/EasyMaze.txt
  src/main/resources/mazes/HardMaze.txt
  src/main/resources/mazes/MediumMaze.txt
Labels: enhancement

#77 Updating enemies
  src/main/java/adapters/default_game/GamePanelController.java
  src/main/java/adapters/default_game/GamePanelPresenter.java
  src/main/java/entities/default_game/Player.java
  src/main/java/use_cases/default_game/IGamePanelInputBoundary.java
  src/main/java/use_cases/default_game/IGamePanelOutputBoundary.java
  src/main/java/use_cases/default_game/MazeInteractor.java
  src/test/java/default_game/CollisionHandlerTest.java
  src/test/java/default_game/PlayerTest.java
Labels: enhancement

#82 Fixed panel switching
  src/main/java/Main.java
  src/main/java/user_interface/default_game/GlobalFrame.java
  src/main/java/user_interface/login_leaderboard/FileReader.java
  src/main/java/user_interface/login_leaderboard/IGlobalFrameOutputBoundary.java
  src/main/java/user_interface/login_leaderboard/Panel.java
  src/main/java/user_interface/login_leaderboard/PanelManager.java
  src/main/java/user_interface/login_leaderboard/WelcomeGlobalFrame.java
Labels: bug, enhancement

#84 Added more options, changed hashmap, cleaned up code
  src/main/java/adapters/default_game/GamePanelController.java
  src/main/java/adapters/default_game/GamePanelPresenter.java
  src/main/java/entities/default_game/Maze.java
  src/main/java/entities/default_game/MazeInfo.java
  src/main/java/use_cases/default_game/CollisionHandler.java
  src/main/java/use_cases/default_game/CustomAssetSetter.java
  src/main/java/use_cases/default_game/IGamePanelInputBoundary.java
  src/main/java/use_cases/default_game/IGamePanelOutputBoundary.java
  src/main/java/use_cases/default_game/IMovePlayerRequest.java
  src/main/java/use_cases/default_game/MazeInteractor.java
  src/main/java/use_cases/default_game/screenManager.java
Labels: bug, enhancement

#88 Stop game thread when user exits maze
  src/main/java/use_cases/default_game/MazeInteractor.java
Labels: bug

#92 New Easy/Medium/HardMaze layouts & adding Sound
  src/main/java/entities/default_game/Sound.java
  src/main/java/use_cases/default_game/CollisionHandler.java
  src/main/java/use_cases/default_game/MazeInteractor.java
  src/main/resources/mazes/EasyMaze.txt
  src/main/resources/mazes/HardMaze.txt
  src/main/resources/mazes/MediumMaze.txt
  src/main/resources/music/gameOver.wav
  src/main/resources/music/pickup_1.wav
  src/main/resources/music/pickup_2.wav
  src/main/resources/music/stageClear.wav
  src/test/java/default_game/SoundTest.java
  src/test/resources/maze04.txt
Labels: enhancement

#100 Fixed merge issue
  src/main/java/Main.java
  src/main/java/adapters/default_game/GamePanelPresenter.java
  src/main/java/user_interface/default_game/GlobalFrame.java
  src/main/java/user_interface/login_leaderboard/PanelManager.java
Labels: bug

#104 Improve Test Coverage
  src/main/java/entities/default_game/Sound.java
  src/main/resources/custom_game_images/obstacle.png
  src/test/java/default_game/CollisionHandlerTest.java
  src/test/java/default_game/MazeInteractorTest.java
  src/test/java/default_game/PlayerTest.java
  src/test/java/default_game/TestGamePanelOutputBoundaryModel.java
  src/test/java/items/ItemTest.java
  src/test/resources/music/gameOver.wav
  src/test/resources/music/pickup_1.wav
  src/test/resources/music/pickup_2.wav
  src/test/resources/music/stageClear.wav
Labels: enhancement

#105 Dealing with new changes in MazeInteractor
  src/main/java/adapters/custom_game/IPlayCustom.java
  src/main/java/user_interface/custom_game/custom_game_file_management/PlayCustom.java
  src/test/java/default_game/MazeInteractorTest.java
  src/test/java/default_game/TestFileOutputBoundary.java
Labels: enhancement

#107 Some minor code fixes
  src/main/java/adapters/default_game/GamePanelController.java
  src/main/java/adapters/login_leaderboard/UsersCreation.java
  src/main/java/frameworks_and_drivers/default_game/GlobalFrame.java
  src/main/java/frameworks_and_drivers/login_leaderboard/FileReader.java
  src/main/java/frameworks_and_drivers/login_leaderboard/PanelManager.java
  src/main/java/frameworks_and_drivers/login_leaderboard/RegisterPanel.java
  src/main/java/tutorial/HelloWorld.java
  src/main/java/use_cases/default_game/CustomAssetSetter.java
  src/main/java/use_cases/login_leaderboard/FileUser.java
  src/main/java/use_cases/login_leaderboard/IFileInputBoundary.java
  src/main/java/use_cases/login_leaderboard/PasswordStrengthChecker.java
  src/test/java/hazards/ChasingEnemyTest.java
  src/test/java/hazards/MovingEnemyTest.java
  src/test/java/tutorial/HelloWorldTest.java
Labels: enhancement
